---
# Configure dnsmasq to work with landrush
- block:
  - name: install dnsmasq
    dnf:
      name: dnsmasq
      state: present
  - name: configure dnsmasq
    template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
      backup: Yes
    notify: restart dnsmasq
  - name: start dnsmasq
    service:
      name: dnsmasq
      state: started
      enabled: Yes
  become: Yes
  become_user: root
  tags:
  - dnsmasq
...
