---
- block:
  - name: enable dnsmasq plugin in NetworkManager
    copy:
      src: nm-dnsmasq.conf
      dest: /etc/NetworkManager/conf.d/00-use-dnsmasq.conf
    notify: restart NetworkManager
  become: True
  become_user: root
  tags:
  - dnsmasq
...
