---
# These tasks fix a bug where the landrush DNS server will not start
# because eventmachine cannot import a module.
- name: gather facts about installed packages
  package_facts:
    manager: auto
- name: get path to eventmachine gem
  find:
    paths: "{{ ansible_user_dir }}/.vagrant.d/gems/{{ ansible_facts.packages['ruby'][0]['version'] }}/gems"
    file_type: directory
    patterns: "eventmachine-*"
  register: eventmachine_path
- name: fix eventmachine gem
  copy:
    src: "{{ eventmachine_path.files[0].path }}/ext/rubyeventmachine.so"
    dest: "{{ eventmachine_path.files[0].path }}/lib/"
    remote_src: True
...
